scrape_configs:
  - job_name: 'Eureka'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8083']
        labels:
          application: 'Eureka Service'
