scrape_configs:
  - job_name: 'Eureka'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8083']
        labels:
          application: 'Eureka Service'
  - job_name: 'Payment'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:7000']
        labels:
          application: 'Payment Service'
  - job_name: 'Product'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Product Service'